/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author fasat
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        barMenuPrinc = new javax.swing.JMenuBar();
        mnIniciar = new javax.swing.JMenu();
        itMnCad = new javax.swing.JMenu();
        itMnCadUsuario = new javax.swing.JMenuItem();
        itMnCadAdministrador = new javax.swing.JMenuItem();
        itMnCadCarro = new javax.swing.JMenuItem();
        itMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nome.setText("Sistema North Cars");

        mnIniciar.setText("Iniciar");

        itMnCad.setText("Cadastrar");

        itMnCadUsuario.setText("Usuário...");
        itMnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadUsuarioActionPerformed(evt);
            }
        });
        itMnCad.add(itMnCadUsuario);

        itMnCadAdministrador.setText("Administrador....");
        itMnCadAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAdministradorActionPerformed(evt);
            }
        });
        itMnCad.add(itMnCadAdministrador);

        itMnCadCarro.setText("Carro...");
        itMnCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCarroActionPerformed(evt);
            }
        });
        itMnCad.add(itMnCadCarro);

        mnIniciar.add(itMnCad);

        itMnSair.setText("Sair");
        itMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairActionPerformed(evt);
            }
        });
        mnIniciar.add(itMnSair);

        barMenuPrinc.add(mnIniciar);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(nome)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        // TODO add your handling code here:
             int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }//GEN-LAST:event_itMnSairActionPerformed

    private void itMnCadAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAdministradorActionPerformed
        // TODO add your handling code here:
        FormCadAdministrador formAdministrador = new FormCadAdministrador();
        formAdministrador.setVisible(true);
    }//GEN-LAST:event_itMnCadAdministradorActionPerformed

    private void itMnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadUsuarioActionPerformed
        // TODO add your handling code here:
        FormCadUsuario formUsuario = new FormCadUsuario();
        formUsuario.setVisible(true);
    }//GEN-LAST:event_itMnCadUsuarioActionPerformed

    private void itMnCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCarroActionPerformed
        // TODO add your handling code here:
        FormCadCarro formCarro = new FormCadCarro();
        formCarro.setVisible(true);
    }//GEN-LAST:event_itMnCadCarroActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JMenu itMnCad;
    private javax.swing.JMenuItem itMnCadAdministrador;
    private javax.swing.JMenuItem itMnCadCarro;
    private javax.swing.JMenuItem itMnCadUsuario;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JMenu mnIniciar;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
